<footer>
	<div class="container">
		<div class="row">
			<div class="span9">
				<h4>PHPSC</h4>
				<p>Grupo de Usu&aacute;rios de PHP do Estado de Santa Catarina</p>
			</div>
			<div class="span3 social_links">
				<a href="http://groups.yahoo.com/group/php-santacatarina/" target="_blank" title="Grupo PHPSC no Yahoo! Grupos">
					<img src="<?php echo $this->getUrl('img/yahoo-groups-icon.png'); ?>" />
				</a>
				<a href="https://www.twitter.com/PHP_SC/" target="_blank" title="PHPSC no Twitter">
					<img src="<?php echo $this->getUrl('img/twitter-icon.png'); ?>" />
				</a>
				<a href="https://www.facebook.com/groups/430320340321421/" target="_blank" title="Grupo PHPSC no Facebook">
					<img src="<?php echo $this->getUrl('img/facebook-icon.png'); ?>" />
				</a>
				<a href="http://www.phpsc.com.br/" target="_blank" title="Blog PHPSC">
					<img src="<?php echo $this->getUrl('img/blog-icon.png'); ?>" />
				</a>
			</div>
		</div>
	</div>
</footer>