<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <meta charset="utf-8">
        <title>PHPSC Conference</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<?php echo $this->getDescription(); ?>">
        <meta name="author" content="Grupo de Usuários de PHP de Santa Catarina">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
        <link href="<?php echo $this->getUrl('css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->getUrl('css/main.css'); ?>" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="<?php echo $this->getUrl('js/vendor/html5shiv.js'); ?>"></script>
            <script src="<?php echo $this->getUrl('js/vendor/respond.min.js'); ?>"></script>
        <![endif]-->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->getBaseUrl(); ?>';
    	</script>
    </head>

    <body>
    	<div id="wrap">
    	   <?php echo $this->renderNavigation(); ?>

        	<div id="main" class="container clear-top">
        	    <div class="row">
                    <div class="span3">
                        <?php echo $this->renderSponsors(); ?>
                    </div>
                    <div class="span9">
                        <?php echo $this->renderContent(); ?>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->renderFooter(); ?>

        <?php foreach ($this->getScripts() as $script) { ?>
            <script src="<?php echo $script; ?>" type="text/javascript"></script>
        <?php } ?>
    </body>
</html>