<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <meta charset="utf-8">
        <title>PHPSC Conference</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<?php echo $this->getDescription(); ?>">
        <link href="<?php echo $this->getBaseUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->getBaseUrl(); ?>/css/main.css" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body>
    	<?php echo $this->renderNavigation(); ?>

    	<div id="wrap">
        	<div id="main" class="container clear-top">
        	    <div class="row">
                    <div class="span3">
                        <?php echo $this->renderSponsors(); ?>
                    </div>
                    <div class="span9">
                        <?php echo $this->renderContent(); ?>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->renderFooter(); ?>

    	<script src="<?php echo $this->getBaseUrl(); ?>/js/jquery-1.7.2.min.js"></script>
    	<script src="<?php echo $this->getBaseUrl(); ?>/js/bootstrap.min.js"></script>
    	<script src="<?php echo $this->getBaseUrl(); ?>/js/twitter.box.js"></script>
    </body>
</html>