<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<div class="btn-group pull-right">
			    <?php if ($user = $this->getTwitterUser()) { ?>
			        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 0px;"><img alt="<?php echo $user->screen_name; ?>"
		                title="Logado como @<?php echo $user->screen_name; ?>"
			            src="<?php echo $user->profile_image_url; ?>"
			            height="30"
			            width="30"></a>
		            <ul class="dropdown-menu">
    					<li><a href="<?php echo $this->getBaseUrl(); ?>/user">Meus dados</a></li>
    					<li><a href="<?php echo $this->getBaseUrl(); ?>/call4papers/submissions">Trabalhos submetidos</a></li>
    					<li class="divider"></li>
    					<li><a href="<?php echo $this->getBaseUrl(); ?>/oauth/logoff">Sair</a></li>
    				</ul>
			    <?php } else { ?>
    				<a class="btn" data-toggle="dropdown" href="<?php echo $this->getBaseUrl(); ?>/oauth/redirect" style="margin-top: 3px">
    				    <i class="icon-user"></i> Logar
    				</a>
				<?php } ?>
			</div>

			<div class="nav-collapse">
				<ul class="nav nav-pills">
				<?php foreach ($this->getOptions() as $option) { ?>
					<li <?php echo $this->isActive($option[1]) ? 'class="active"' : ''; ?>>
				        <a href="<?php echo $this->getBaseUrl() . $option[1]; ?>"><?php echo $option[0]; ?></a>
		            </li>
				<?php } ?>
				</ul>
			</div>
		</div>
	</div>
</div>