<div id="<?= $this->getContainerId(); ?>" class="btn-group <?= $this->getContainerClass(); ?>">
    <a class="btn dropdown-toggle <?= $this->getButtonClass(); ?>" data-toggle="dropdown" href="#">
        <i class="icon-share icon-white"></i> Compartilhar <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" style="min-width: 120px; text-align: left;">
    <?php foreach ($this->getLinks() as $provider => $uri) { ?>
        <li><a href="<?= $uri ?>" target="_blank"><?= $provider ?></a></li>
        <?php } ?>
    </ul>
</div>