<a href="<?php echo $this->getBaseUrl(); ?>">
    <img id="logo" src="<?php echo $this->getBaseUrl(); ?>/img/logo.png"
        alt="PHP Santa Catarina" border="0" />
</a>
<div class="hero-unit" id="sponsors">
    <h3>Patrocínio e Apoio</h3>
    <div style="margin-left: 15px; margin-top: 10px;">
        <h4><i class="icon-star-empty"></i> Diamond</h4>
        <h6>-</h6>
        <h4><i class="icon-star-empty"></i> Gold</h4>
        <h6>-</h6>
        <h4><i class="icon-star-empty"></i> Silver</h4>
        <h6>-</h6>
        <h4><i class="icon-star-empty"></i> Apoio</h4>
        <h6>-</h6>
    </div>
</div>