<a href="<?php echo $this->getBaseUrl(); ?>">
    <img id="logo" src="<?php echo $this->getBaseUrl(); ?>/img/logo.png"
        alt="PHP Santa Catarina" border="0" />
</a>
<div class="hero-unit" id="sponsors">
    <h3>Apoio</h3>
    <div style=" margin-top: 10px;">
        <a href="http://www.univali.br" target="_blank" ><img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_univali.gif" alt='Universidade do Vale do Itajaí'></a>
        <a href="http://www.novatec.com.br" target="_blank"><img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_novatec.gif" alt='Editora Novatec'></a>
        <a href="http://www.schoolofnet.com" target="_blank"><img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_schoolofnet.gif" alt='School Of Net'></a>
        <a href="http://www.zfnapratica.com.br" target="_blank"><img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_zfnapratica.gif" alt='Zend Framework Na Prática'></a>
    </div>
</div>