<div id="fb-root"></div>
<script type="text/javascript">
(
function(d, s, id)
{
    var js, fjs = d.getElementsByTagName(s)[0];

    if (d.getElementById(id)) {
        return;
    }

    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div class="jumbotron">
    <div class="container">
        <h1>
            PHPSC Conference 2013<br />
            <small>25 e 26 de outubro de 2013, Unochapecó, Chapecó, SC</small>
        </h1>
        <p>
            <a class="btn btn-primary btn-lg" href="<?php echo $this->getUrl('about'); ?>">Maiores Informações &raquo;</a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
    <?php if ($this->isSubmissionInterval()) { ?>
        <h2>Chamada de Trabalhos</h2>
        <p>Está aberta a Chamada de Trabalhos</p>
        <p><a class="btn btn-info" href="<?php echo $this->getUrl('call4papers/'); ?>">Enviar trabalho &raquo;</a></p>
    <?php } elseif ($this->isApprovalPeriod()) { ?>
        <h2>Chamada de Trabalhos</h2>
        <p>Os trabalhos estão em avalição, e você pode nos ajudar!</p>
        <p><a class="btn btn-info" href="<?php echo $this->getUrl('call4papers/feedback'); ?>">Votar nas palestras &raquo;</a></p>
    <?php } else { ?>
        <h2>Programação do evento</h2>
        <p>A grade de palestras aprovadas foi liberada, confira agora!</p>
        <p><a class="btn btn-info" href="<?php echo $this->getUrl('talks'); ?>">Ver palestras &raquo;</a></p>
    <?php } ?>
    </div>
    <div class="col-md-6">
        <h2>Inscrições</h2>
    <?php if ($this->isApprovalPeriod()) { ?>
        <p>Super promoção para inscrições antecipadas, aproveite!</p>
    <?php } elseif ($this->isRegularRegistrationPeriod()) { ?>
        <p>
            O período de inscrições promocionais foi finalizado, mas ainda dá
            tempo de você participar do evento pagando um valor mais em conta
            que as inscrições no dia do evento!
        </p>
    <?php } elseif ($this->isLateRegistrationPeriod()) { ?>
        <p>
            Você ainda pode realizar sua inscrição, porém deverá pagar o preço de inscrições tardias!
        </p>
    <?php } else { ?>
        <p>
            O período de inscrições foi finalizado, não será mais possível você se inscrever para este evento.
        </p>
    <?php } ?>
        <p><a class="btn btn-info" href="<?php echo $this->getUrl('registration'); ?>">Maiores Informações &raquo;</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h2>PHPSC nas redes sociais</h2>
        </div>
        <dir class="row text-left">
            <div class="col-md-6">
                <div id="twitterBox">
                    <a class="twitter-timeline" href="https://twitter.com/search?q=%23phpscconf+OR+%40PHP_SC" data-widget-id="371282499042701313">Tweets sobre "#phpscconf OR @PHP_SC"</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                </div>
            </div>
            <div class="col-md-6">
                <div class="fb-like-box" data-href="https://www.facebook.com/pages/PHP-Santa-Catarina/478179522208583" data-width="440" data-height="300" data-show-faces="true" data-stream="false" data-header="false">
                </div>
            </div>
        </dir>
    </div>
</div>