<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <meta charset="utf-8">
        <title>PHPSC Conference - Status</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Acompanhe o status das inscrições e presenças ao vivo!">
        <link href="<?php echo $this->getUrl('css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->getUrl('css/main.css'); ?>" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->getBaseUrl(); ?>';
    	</script>
    	<script src="<?php echo $this->getUrl('js/vendor/jquery-1.10.2.min.js'); ?>" type="text/javascript"></script>
    	<script src="<?php echo $this->getUrl('js/vendor/bootstrap.min.js'); ?>" type="text/javascript"></script>
    	<script src="<?php echo $this->getUrl('js/status.js'); ?>" type="text/javascript"></script>
    	<script src="<?php echo $this->getUrl('js/supporters.list.js'); ?>" type="text/javascript"></script>
    	<style type="text/css">
            body {
            	background-color: #F5F5F5;
            }

            #nrInscricoes, #nrPresencas {
                color: #27519d;
                text-align: center;
            }

            h4 {
            	padding-top: 35px;
            }
    	</style>
    </head>

    <body>
        <div>
        	<div class="container" style="padding-top: 30px;">
        	    <div class="row">
                    <div class="col-md-12" style="text-align: center;">
                        <img src="<?php echo $this->getUrl('img/logo-grande.png'); ?>" alt="PHPSC Conference 2012" height="250" />
                    </div>
                </div>
        	    <div class="row" style="padding-top: 30px">
                    <div class="col-md-2 col-md-offset-3"><h2 id="nrInscricoes"></h2></div>
                    <div class="col-md-2 col-md-offset-2"><h2 id="nrPresencas"></h2></div>
                </div>
            </div>
        </div>
        <div style="background-color: white; margin-top: 60px">
            <div class="container">
                <?= $this->getSponsors(); ?>
            </div>
        </div>
    </body>
</html>