<div class="row">
    <div class="col-md-2">
        <a href="<?= $this->getBaseUrl(); ?>">
            <img alt="PHPSC Conference" src="<?= $this->getUrl('img/logo.png'); ?>" />
        </a>
    </div>
    <div class="col-md-10">
        <header class="page-header" style="padding-top: 30px; padding-left: 15px;">
            <h1>O Local</h1>
        </header>
    </div>
</div>
<div class="row" style="padding-top: 10px;">
    <div class="<?= $this->displayMap() ? 'col-md-5' : 'col-md-12'; ?>">
        <p>Esse ano, o evento será realizado em Chapecó na Unochapecó.</p>
        <p style="margin-top: 10px;">
            <strong>Campus Chapecó</strong><br/>
            Av. Senador Attílio Fontana, 591-E<br />
            Efapi - Chapecó - Santa Catarina<br />
        </p>
    </div>
    <?php if ($this->displayMap()) { ?>
    <div class="col-md-7">
        <div class="thumbnail">
            <div id="mapEvento"></div>
            <h6 id="address"></h6>
        </div>
    </div>
    <?php } ?>
</div>
<?php if ($this->displayMap()) { ?>
<script type="text/javascript">
    var lat = <?php echo $this->getEvent()->getLocation()->getLatitude(); ?>;
    var lng = <?php echo $this->getEvent()->getLocation()->getLongitude(); ?>;
</script>
<?php } ?>