<?php /* @var $this PHPSC\Conference\UI\Admin\Supporters\Grid */ ?>
<div class="row" style="margin-bottom: 20px;">
    <div class="col-md-6">
        <h2>
            Gerenciando apoiadores<br />
            <small><?= $this->event->getName(); ?></small>
        </h2>
    </div>
    <div class="col-md-6" style="text-align: right">
        <div class="btn-group pull-right" style="margin-left: 10px;">
            <a class="btn btn-primary" href="javascript:;" id="addSupporter">
                <span class="glyphicon glyphicon-certificate"></span>
                Novo apoiador
            </a>
        </div>
    </div>
</div>
<div id="confirmationMsg" class="row hide">
    <div class="col-md-12">
        <div class="alert alert-block alert-info">
            <h4 class="alert-heading"></h4>
            <span></span>
        </div>
    </div>
</div>
<?= $this->getDatagrid(); ?>
<?= $this->getSupporterModal(); ?>