<div class="row" style="margin-bottom: 20px;">
    <div class="col-md-6">
        <h2>
            Gerenciando apoiadores<br />
            <small><?= $this->getEvent()->getName(); ?></small>
        </h2>
    </div>
    <div class="col-md-6" style="text-align: right">
        <div class="btn-group pull-right" style="margin-left: 10px;">
            <a class="btn btn-primary" href="javascript:;" id="addSupporter">
                <span class="glyphicon glyphicon-certificate"></span>
                Novo apoiador
            </a>
        </div>
    </div>
</div>
<?= $this->getDatagrid(); ?>
<?= $this->getSupporterModal(); ?>