<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style type="text/css">
body {
	margin: 0;
	background-color: #F0EBE2;
	text-align: center;
	font-size: 12px;
	font-family: Tahoma, Verdana, sans-serif;
	color: #444444;
}

#container {
	border: 1px solid #AAAAAA;
	background-color: #FFFFFF;
	padding: 40px;
	width: 80%;
	margin: auto;
	margin-top: 53px;
	text-align: left;
}

h1 {
	font-size: 20px;
	font-weight: bold;
	padding-bottom: 4px;
	border-bottom: 1px solid #AAAAAA;
	margin-bottom: 5px;
}

h2 {
	font-size: 14px;
	margin: 0px;
	padding-bottom: 10px;
}

#trace {
	overflow-y: auto;
	margin-top: 10px;
	padding: 8px;
	border: 1px solid #CCCCCC;
	height: auto;
	max-height: 350px;
	text-align: left;
	white-space: pre;
}
</style>
</head>
<body>
    <div id="container">
        <h1>Error {statusCode}</h1>
        <h2>{message}</h2>
        <div>
            Further information:
            <div id="trace">{trace}</div>
        </div>
    </div>
</body>
</html>