<div class="jumbotron" style="padding: 30px;">
    <?php if (!$this->getAttendee()->isWaitingForPayment()) { ?>
    <h2>Você já está inscrito!</h2>
    <p style="margin-left: 10px; text-align: justify;">Sua inscrição no <?php echo $this->getEvent()->getName(); ?> está registrada com sucesso.</p>
    <div style="margin-top: 15px;">
        <p>Não perca tempo, convide seus amigos para participar deste evento também!</p>
        <p><?= $this->getShareButton(); ?></p>
    </div>
    <?php } else { ?>
    <h2>Atenção!</h2>
    <p style="margin-left: 10px; text-align: justify;">
        Sua inscrição no <?php echo $this->getEvent()->getName(); ?> foi registrada, entretanto seu pagamento ainda não foi confirmado.
    </p>
    <p style="margin-left: 10px; text-align: justify;">
        Caso você já tenha realizado o pagamento através do PagSeguro, em breve receberemos a confirmação e esta mensagem não aparecerá novamente.
    </p>
    <p style="margin-left: 10px; text-align: justify;">
        Se ocorreu algum problema durante o pagamento e você não foi capaz de concluí-lo, clique no botão abaixo!
    </p>
    <p><a class="btn btn-primary btn-lg" href="#pay" data-toggle="modal"><span class="glyphicon glyphicon-shopping-cart"></span> Efetuar pagamento</a></p>
    <?php } ?>
</div>
<div id="pay" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pay" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3>Reenviar pagamento</h3>
            </div>
            <div class="modal-body">
                <div id="payMsg" class="alert alert-danger hide">
                    <h4></h4>
                </div>
                <h4 style="margin-bottom: 10px;">Você deseja realmente solicitar o pagamento da inscrição?</h4>
                <p style="margin: 0px 10px;">
                    Você será redirecionado para o PagSeguro, realize todos os passos atentamente!
                    Caso ocorra algum problema você poderá solicitar um novo pagamento através desta página.
                </p>
            </div>
            <div id="payButtons" class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Não</button>
                <button id="payConfirm" class="btn btn-primary">Sim</button>
            </div>
        </div>
    </div>
</div>