<?php /* @var $this PHPSC\Conference\UI\Pages\Registration\Confirmation */ ?>
<div class="jumbotron" style="padding: 30px;">
    <h2>Parabéns!</h2>
    <p>Sua inscrição no <?php echo $this->event->getName(); ?> foi registrada com sucesso.</p>
    <div style="margin-top: 15px;">
        <p>Não perca tempo, convide seus amigos para participar deste evento também!</p>
        <p><?= $this->getShareButton(); ?></p>
    </div>
</div>