<form role="form" id="attendeeForm" class="well" action="<?php echo $this->getUrl('registration'); ?>" method="post">
    <fieldset>
        <legend>Inscrição - <?php echo $this->getEvent()->getName(); ?></legend>
        <div class="formItems">
            <?php if ($this->isSpeakerWithApprovedTalks()) { ?>
            <div class="alert alert-info">
                <h4 class="alert-heading">Prezado palestrante</h4>
                <span>Você não precisa realizar a inscrição, pois elá já foi realizada automaticamente.</span>
            </div>
            <?php } elseif ($this->isSpeakerAndApprovalIntervalIsNotFinished()) { ?>
            <div class="alert alert-info">
                <h4 class="alert-heading">Atenção</h4>
                <p>
                    Sabemos que você deseja muito participar deste evento,
                    mas suas palestas ainda não foram analisadas. Aguarde mais um pouco. <br />
                    Caso suas palestas não forem aprovadas, você terá tempo para fazer sua inscrição com desconto.
                </p>
            </div>
            <?php } else { ?>
            <div class="alert alert-info">
                <h4 class="alert-heading">Prezado participante</h4>
                <span>Leia com atenção os <a href="#terms" data-toggle="modal">termos de participacão</a>!</span>
            </div>
            <div>
                <h3>Valores</h3>
                <p>O valor da inscrição para as palestras muda de acordo com o período em que a inscrição é realizada.</p>
                <p>
                    <strong>Inscrições antecipadas</strong> possuem desconto, e são aquelas que ocorreram antes da aprovação de ao menos uma
                    palestra no sistema (a data final de submissão de trabalhos é <?php echo $this->getEvent()->getSubmissionEnd()->format('d/m/Y H:i:s'); ?>).
                </p>
                <p>As inscrições realizadas após este período são as <strong>inscrições regulares</strong>.</p>
                <p>No dia do evento também aceitaremos <strong>inscrições tardias</strong>, porém custarão mais que as <strong>inscrições antecipadas</strong> ou <strong>regulares</strong>.</p>
            </div>
            <div>
                <p id="regularAttendee">
                    O custo da sua inscrição para as palestras será de <strong>R$ <?php echo number_format($this->getCost(), 2, ',', '.'); ?></strong>, devendo ser pago
                    através do PagSeguro (de acordo com os <a href="#terms" data-toggle="modal">termos de participacão</a>).
                </p>
                <p id="studentAttendee" class="hide">A sua inscrição para as palestras será gratuita.</p>
            </div>
            <?php if ($this->getEvent()->getRegistrationInfo()->hasStudentDiscount()) { ?>
            <div class="form-group">
                <input id="isStudent" name="isStudent" type="checkbox" />
                <label for="isStudent" style="display: inline;"><?php echo $this->getEvent()->getRegistrationInfo()->getStudentLabel(); ?></label>
            </div>
            <?php } ?>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary">Concordo com os termos e desejo participar &raquo;</button>&nbsp;&nbsp;
                    <a href="<?php echo $this->getUrl('registration'); ?>" class="btn btn-default">Cancelar</a>
                </div>
            </div>
            <?php } ?>
        </div>
    </fieldset>
</form>
<div id="terms" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="terms" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3>Termos de participação</h3>
            </div>
            <div class="modal-body">
                <h4 style="margin: 10px 0px;">Minicursos</h4>
                <p style="text-align: justify; margin-left: 15px;">
                    No evento, poderão ser ofertados minicursos.
                    A inscrição e o pagamento dos minicursos deverá ser realizada pessoalmente, no dia do evento (durante o credenciamento).
                </p>
                <h4 style="margin-bottom: 10px;">Pagamento (palestras)</h4>
                <p style="text-align: justify; margin-left: 15px;">
                    O pagamento da inscrição para as palestras deverá ser realizado através do PagSeguro,
                    utilizando a conta pessoal de um dos coordenadores do PHPSC. Isto se dá pelos seguintes motivos:
                </p>
                <div style="text-align: justify; margin-left: 15px;">
                    <ol>
                		<li>O PagSeguro facilita o pagamento, pois é seguro, tanto para quem paga, como para quem recebe;</li>
                		<li>O PHPSC é um grupo sem fins lucrativos, formado por profissionais do estado de Santa Catarina, não sendo uma entidade jurídica.</li>
                	</ol>
            	</div>
            	<p style="text-align: justify; margin-left: 15px;">
            	    O pagamento da inscrição no evento <strong>apenas dá direito ao participante de assistir as palestras</strong>.
            	    Caso o participante tenha interesse nos minicursos, ele deverá se inscrever e realizar o pagamento destes
            	    no dia do evento (durante o credenciamento).
        	    </p>
                <h4 style="margin: 10px 0px;">Sigilo das informações</h4>
                <p style="text-align: justify; margin-left: 15px;">
                    O PHPSC manterá sigilo absoluto a respeito das informações pessoais dos participantes do evento
                    para apenas os envolvidos na organização, divulgando publicamente somente os números de participantes
                    inscritos e os resultados do evento.
                </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
<?php if ($this->getEvent()->getRegistrationInfo()->hasStudentDiscount()) { ?>
<div id="studentRules" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="studentRules" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3>Atenção</h3>
            </div>
            <div class="modal-body">
                <?php echo $this->getEvent()->getRegistrationInfo()->getStudentRules(); ?>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" id="revertIsStudent" data-dismiss="modal">Não sou aluno</button>
                <button class="btn btn-primary" data-dismiss="modal">Sou aluno e levarei o comprovante de matrícula</button>
            </div>
        </div>
    </div>
</div>
<?php } ?>
