<?php /* @var $this PHPSC\Conference\UI\Pages\Registration\Index */ ?>
<div class="jumbotron">
    <h2>Inscrições de participantes</h2>
    <h3><?php echo $this->event->getName(); ?></h3>
    <div style="margin-top: 15px;">
        <?php if (!$this->event->hasAttendeeRegistration()) { ?>
            <p>Ainda não foram registrados as datas de inscrição de participantes, aguarde!</p>
        <?php } elseif (!$this->event->isRegistrationInterval(new \DateTime())) { ?>
            <p>Não está no período de inscrições!</p>
            <p>Data Início: <strong><?php echo $this->event->getRegistrationInfo()->getStart()->format('d/m/Y H:i'); ?></strong>
            <br />Data Fim: <strong><?php echo $this->event->getRegistrationInfo()->getEnd()->format('d/m/Y H:i'); ?></strong></p>
        <?php } else { ?>
            <p>Está aberta a inscrição, não perca tempo e garanta seu lugar no evento!</p>
            <p><a class="btn btn-primary btn-lg" href="<?php echo $this->getUrl('registration/new'); ?>">Participar &raquo;</a></p>
        <?php } ?>
    </div>
</div>
<?php if ($this->event->hasAttendeeRegistration()) { ?>
<div class="row">
    <div class="col-md-9">
        <h2>Maiores informações</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <h3>Estudantes</h3>
        <?= $this->getStudentRules(); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <h3>Palestrantes</h3>
        <p>A inscrição de palestrantes com propostas aprovadas será <strong>automática</strong>, não sendo necessário nenhuma intervenção.</p>
        <p>Os palestrantes que não tiverem nenhuma proposta aprovada, deverão realizar a inscrição a partir de <strong><?php echo $this->event->getTalkApprovalEnd()->format('d/m/Y H:i:s'); ?></strong>.</p>
    </div>
</div>
<?php } ?>