<div class="hero-unit" style="padding: 30px;">
    <?php if (!$this->getAttendee()->isPaymentRequired()) { ?>
    <h2>Você já está inscrito!</h2>
    <p style="margin-left: 10px; text-align: justify;">Sua inscrição no <?php echo $this->getEvent()->getName(); ?> está registrada com sucesso.</p>
    <div style="margin-top: 15px;">
        <p>Não perca tempo, convide seus amigos para participar deste evento também!</p>
        <p><a class="btn btn-info btn-large" href="#share" data-toggle="modal"><i class="icon-share icon-white"></i> Compartilhar</a></p>
    </div>
    <?php } else { ?>
    <h2>Atenção!</h2>
    <p style="margin-left: 10px; text-align: justify;">
        Sua inscrição no <?php echo $this->getEvent()->getName(); ?> foi registrada, entretanto seu pagamento ainda não foi confirmado.
    </p>
    <p style="margin-left: 10px; text-align: justify;">
        Caso você já tenha realizado o pagamento através do PagSeguro, em breve receberemos a confirmação e esta mensagem não aparecerá novamente.
    </p>
    <p style="margin-left: 10px; text-align: justify;">
        Se ocorreu algum problema durante o pagamento e você não foi capaz de concluí-lo, clique no botão abaixo!
    </p>
    <p><a class="btn btn-primary btn-large" href="#pay" data-toggle="modal"><i class="icon-shopping-cart icon-white"></i> Efetuar pagamento</a></p>
    <?php } ?>
</div>
<div id="share" class="modal hide fade" style="display: none; ">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Compartilhar inscrição</h3>
    </div>
    <div class="modal-body">
        <div id="shareMsg" class="alert alert-error hidden">
            <h4></h4>
        </div>
        <h4 style="margin-bottom: 10px;">Você concorda com o envio de um tweet com o conteúdo abaixo?</h4>
        <p style="margin: 0px 10px;">
            <q>Acabo de me inscrever no #phpscConf. Participe você
            também através do site http://cfp.phpsc.com.br! via @PHP_SC</q>
        </p>
    </div>
    <div id="shareButtons" class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancelar</button>
        <button id="shareConfirm" class="btn btn-primary">Concordo</button>
    </div>
</div>
<div id="pay" class="modal hide fade" style="display: none; ">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Reenviar pagamento</h3>
    </div>
    <div class="modal-body">
        <div id="payMsg" class="alert alert-error hidden">
            <h4></h4>
        </div>
        <h4 style="margin-bottom: 10px;">Você deseja realmente solicitar o pagamento da inscrição?</h4>
        <p style="margin: 0px 10px;">
            Você será redirecionado para o PagSeguro, realize todos os passos atentamente!
            Caso ocorra algum problema você poderá solicitar um novo pagamento através desta página.
        </p>
    </div>
    <div id="payButtons" class="modal-footer">
        <button class="btn" data-dismiss="modal">Não</button>
        <button id="payConfirm" class="btn btn-primary">Sim</button>
    </div>
</div>