<?php /* @var $this PHPSC\Conference\UI\Pages\Call4Papers\Index */ ?>
<div class="jumbotron" style="padding: 30px;">
    <h2>Chamada de trabalhos</h2>
    <h3><?php echo $this->event->getName(); ?></h3>
    <div style="margin-top: 15px;">
        <?php if (!$this->event->hasTalkSubmissions()) { ?>
            <p>Os trabalhos deste evento serão cadastrados internamente, fique atento às novidades!</p>
        <?php } elseif (new \DateTime() < $this->event->getSubmissionStart()) { ?>
            <p>Ainda não está aberta a submissão de trabalhos, aguarde mais um pouco!</p>
            <p>Você poderá enviar suas palestras a partir de <strong><?php echo $this->event->getSubmissionStart()->format('d/m/Y H:i'); ?></strong></p>
        <?php } elseif (new \DateTime() > $this->event->getSubmissionEnd()) { ?>
            <p>A submissão de trabalhos foi finalizada em <strong><?php echo $this->event->getSubmissionEnd()->format('d/m/Y H:i'); ?></strong>.</p>
            <p>Agradecemos a participação de todos, em breve o resultado da avaliação de suas palestras estará disponível na
                <a href="<?php echo $this->getUrl('call4papers/submissions'); ?>">lista de trabalhos submetidos</a>.
            </p>
        <?php } else { ?>
            <p>Está aberta a chamada de trabalhos, não perca tempo e envie sua proposta de palestra!</p>
            <p><a class="btn btn-primary btn-lg" href="<?php echo $this->getUrl('call4papers/submissions/new'); ?>">Desejo contribuir &raquo;</a></p>
        <?php } ?>
    </div>
</div>
<?php if ($this->event->isSubmissionsPeriod(new \DateTime())) { ?>
<div class="row">
    <div class="col-md-9">
        <h3 style="margin-bottom: 10px;">Maiores informações</h3>
        <p>As propostas serão aceitas até <strong><?php echo $this->event->getSubmissionEnd()->format('d/m/Y H:i'); ?></strong>, após
            esta data passarão pela avaliação dos membros do <strong>PHPSC</strong> e também da comunidade.</p>
        <p>Os palestrantes terão acesso às análises de todos os trabalhos submetidos.</p>
        <p>A grade de propostas aprovadas será disponibilizada neste site após o período de submissão de trabalhos.</p>
        <p>
            <a class="btn btn-sm btn-primary" href="<?php echo $this->getUrl('call4papers/submissions/new'); ?>">Enviar proposta &raquo;</a>&nbsp;&nbsp;
            <a class="btn btn-sm btn-default" href="<?php echo $this->getUrl('call4papers/submissions'); ?>">Meus trabalhos submetidos &raquo;</a></p>
    </div>
</div>
<?php } ?>