<?php /* @var $this PHPSC\Conference\UI\Pages\Call4Papers\TalkWindow */ ?>
<link href="<?php echo $this->getUrl('css/selectize.bootstrap3.css'); ?>" rel="stylesheet">
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <?php if (!$this->isReadOnly()) { ?>
                    <h3>Editando trabalho</h3>
                <?php } else { ?>
                    <h3>Visualizando trabalho</h3>
                <?php } ?>
            </div>
            <form role="form" id="editForm" action="" style="margin: 0px;">
                <div class="modal-body">
                    <fieldset>
                        <div class="formItems" style="padding-top: 0px;">
                            <div class="alert alert-block hide">
                                <h4 class="alert-heading"></h4>
                                <span></span>
                            </div>
                            <div class="form-group">
                                <label for="title">Título</label>
                                <input type="text" required="required" id="title" name="title" class="form-control" placeholder="Digite o título da palestra..." maxlength="120"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                            </div>
                            <div class="form-group">
                                <label for="type">Tipo de trabalho</label>
                                <select id="type" name="type" class="form-control"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                                    <option value="2">Palestra (duração: 50 minutos)</option>
                                    <option value="3">Palestra Curta (duração: 15 minutos)</option>
                                    <option value="1">Minicurso (duração: 4 horas)</option>
                                    <option value="5">Minicurso Longo (duração: 8 horas)</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="complexity">Nível</label>
                                <select id="complexity" name="complexity" class="form-control"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                                    <option value="L">Básico</option>
                                    <option value="M">Intermediário</option>
                                    <option value="H">Avançado</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="shortDescription">Resumo</label>
                                <textarea rows="2" cols="1" class="form-control" id="shortDescription" name="shortDescription" placeholder="Esse resumo será usado para divulgação da palestra na grade. Venda seu peixe!"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>></textarea>
                            </div>
                            <div class="form-group">
                                <label for="longDescription">Descrição</label>
                                <textarea rows="2" cols="1" class="form-control" id="longDescription" name="longDescription" placeholder="Detalhe mais sua palestra, usaremos essas informações para avaliá-la."<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>></textarea>
                            </div>
                            <div class="form-group">
                                <label for="tags">Palavras-chave</label>
                                <input type="text" id="tags" name="tags" class="form-control" placeholder="Digite as palavras-chave da palestra (separadas por vírgula)..." maxlength="120"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <?php if (!$this->isReadOnly()) { ?>
                        <button class="btn btn-primary">Salvar</button>
                    <?php } ?>
                    <a href="#" class="btn btn-default" data-dismiss="modal">Fechar</a>
                </div>
            </form>
        </div>
    </div>
</div>