<div class="row" style="margin-bottom: 20px;">
    <div class="span5">
        <h2>Meus trabalhos submetidos</h2>
    </div>
    <div class="span4" style="text-align: right">
        <?php if ($this->allowSubmission()) { ?>
        <div class="btn-group pull-right" style="margin-left: 10px;">
            <a class="btn btn-primary" href="<?php echo $this->getUrl('call4papers/submissions/new'); ?>"><span class="glyphicon glyphicon-certificate"></span> Novo trabalho</a>
        </div>
        <?php } ?>
        <?= $this->getShareButton(); ?>
    </div>
</div>
<div id="gridMsg" class="alert alert-info">
    <h4 class="alert-heading">Atenção</h4>
    <span>Nesta página você visualizará informações sobre os trabalhos que você submeteu.</span>
</div>
<?php echo $this->getDatagrid(); ?>
<?php echo $this->getTalkModal(); ?>