<div id="share" class="modal hide fade" style="display: none; ">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Compartilhar submissões</h3>
    </div>
    <div class="modal-body">
        <div id="shareMsg" class="alert alert-error hidden">
            <h4></h4>
        </div>
        <h4 style="margin-bottom: 10px;">Você concorda com o envio de um tweet com o conteúdo abaixo?</h4>
        <p style="margin: 0px 10px;">
            <q>Estou colaborando no #phpscConf com <?php echo $this->getTalksCount(); ?> trabalho(s). Contribua você
            também através do site http://cfp.phpsc.com.br! via @PHP_SC</q>
        </p>
    </div>
    <div id="shareButtons" class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancelar</button>
        <button id="shareConfirm" class="btn btn-primary">Concordo</button>
    </div>
</div>
<div class="row" style="margin-bottom: 20px;">
    <div class="span5">
        <h2>Meus trabalhos submetidos</h2>
    </div>
    <div class="span4" style="text-align: right">
        <?php if ($this->hasTalks()) { ?>
            <a class="btn btn-info" href="#share" data-toggle="modal"><i class="icon-share icon-white"></i> Compartilhar</a>
        <?php } ?>
        <?php if ($this->allowSubmission()) { ?>
            <a class="btn btn-primary" href="<?php echo $this->getBaseUrl(); ?>/call4papers/submissions/new"><i class="icon-certificate icon-white"></i> Novo trabalho</a>
        <?php } ?>
    </div>
</div>
<div id="gridMsg" class="alert alert-info">
    <h4 class="alert-heading">Atenção</h4>
    <span>Nesta página você visualizará informações sobre os trabalhos que você submeteu.</span>
</div>
<?php echo $this->getDatagrid(); ?>
<?php echo $this->getTalkModal(); ?>