<div class="modal hide" id="edit">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <?php if (!$this->isReadOnly()) { ?>
            <h3>Editando trabalho</h3>
        <?php } else { ?>
            <h3>Visualizando trabalho</h3>
        <?php } ?>
    </div>
    <form id="editForm" action="" style="margin: 0px;">
        <div class="modal-body">
            <fieldset>
                <div class="formItems" style="padding-top: 0px;">
                    <div class="alert alert-block hide">
                        <h4 class="alert-heading"></h4>
                        <span></span>
                    </div>
                    <label for="title">Título</label>
                    <input type="text" required="required" id="title" name="title" class="span5" placeholder="Digite o título da palestra..." maxlength="120"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                    <label for="type">Tipo de trabalho</label>
                    <select id="type" name="type" class="span5"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                        <option value="2">Palestra (duração: 50 minutos)</option>
                        <option value="3">Palestra Curta (duração: 15 minutos)</option>
                        <option value="1">Minicurso (duração: 4 horas)</option>
                    </select>
                    <label for="complexity">Nível</label>
                    <select id="complexity" name="complexity" class="span5"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                        <option value="L">Básico</option>
                        <option value="M">Intermediário</option>
                        <option value="H">Avançado</option>
                    </select>
                    <label for="shortDescription">Resumo</label>
                    <textarea rows="2" cols="1" class="span5" id="shortDescription" name="shortDescription" placeholder="Esse resumo será usado para divulgação da palestra na grade. Venda seu peixe!"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>></textarea>
                    <label for="longDescription">Descrição</label>
                    <textarea rows="2" cols="1" class="span5" id="longDescription" name="longDescription" placeholder="Detalhe mais sua palestra, usaremos essas informações para avaliá-la."<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>></textarea>
                    <label for="tags">Palavras-chave</label>
                    <input type="text" id="tags" name="tags" class="span5" placeholder="Digite as palavras-chave da palestra (separadas por vírgula)..." maxlength="120"<?php if ($this->isReadOnly()) { ?> disabled="disabled"<?php } ?>>
                </div>
            </fieldset>
        </div>
        <div class="modal-footer">
            <?php if (!$this->isReadOnly()) { ?>
                <button class="btn btn-primary">Salvar</button>
            <?php } ?>
            <a href="#" class="btn" data-dismiss="modal">Fechar</a>
        </div>
    </form>
</div>