<?php if (!$this->hasApprovedTalks()) { ?>
<div class="hero-unit" style="padding: 30px;">
    <h2>Grade de palestras</h2>
    <h3><?php echo $this->getEvent()->getName(); ?></h3>
    <div style="margin-top: 15px;">
        <p>As palestras estão em avaliação, aguarde!</p>
    </div>
</div>
<div class="row">
    <div class="span9">
        <h2>Você pode ajudar!</h2>
        <p>
            Sim, você também pode colaborar no processo de avaliação de palestras!<br />
            Para fazer isto, basta dar sua opinião <a href="<?php echo $this->getBaseUrl() ?>/call4papers/feedback">aqui</a>!
        </p>
    </div>
</div>
<?php } else { ?>
<div class="row title">
    <div class="span9">
        <h1>Grade de palestras</h1>
        <h3><?php echo $this->getEvent()->getName(); ?></h3>
    </div>
</div>
<div class="row">
    <div class="span9">
        <table class="table table-striped">
            <caption style="font-size:14px; margin: 0; font-weight: bold;">Palestras</caption>
			<thead>
				<tr>
					<th class="span1"></th>
					<th class="span4">Auditório</th>
					<th class="span4">Sala</th>
				</tr>
			</thead>
			<tbody>
				<tr>
				    <th class="span1">09:00</th>
					<td class="descricao" data-owner="Domingos Teruel" data-desc="O objetivo desta da palestra é debater as expectativas do mercado de desenvolvimento ao contratar um profissional PHP, sendo assim a palestra irá abordar o que era o PHP e o que está acontecendo com o PHP nos últimos anos, quais tecnologias e frameworks.">Profissão: Programador PHP</td>
					<td class="descricao rightColumn" data-owner="Alex Piaz" data-desc="Uma interessante viagem pelo processo de decisão pelo uso de um CMS. Nesta palestra você irá aprender quais passos deve seguir se precisar optar pelo uso de um CMS (Sistema Gerenciador de Conteúdo) para sua empresa/organização. O que é preciso avaliar, quais cuidados tomar e tudo mais. E claro, você vai saber porque o Drupal foi escolhido.">Destino final: Drupal</td>
				</tr>
				<tr>
				    <th class="span1">10:00</th>
					<td class="descricao" data-owner="Alexandre Gaigalas" data-desc="Re-escrita de software é um problema comum. Boa parte dos programadores com alguma experiência já passaram por projetos de re-escrita. Essa palestra mostra como pequenas decisões no dia-a-dia podem ajudar a tornar seu projeto mais extensível, modular e flexível, pronto para ser aprimorado sem ser re-escrito. Essas pequenas decisões que garantem a durabilidade envolvem escolhas comuns para clareza da API, testes, tecnologias envolvidas, padrões e convenções de mercado, versionamento e modularização.">Criação de Software para Durar</td>
					<td class="descricao rightColumn" data-owner="Domingos Teruel" data-desc="Uma introdução à programação orientada a objeto em PHP focada no desenvolvimento de plugins para Wordpress.">Programação Orientada a Objetos para o desenvolvimento de Plugins para WordPress</td>
				</tr>
				<tr>
				    <th class="span1">11:00</th>
					<td class="descricao" data-owner="Augusto Pascutti" data-desc="Uma introdução ao desenvolvimento orientado a testes de forma prática: com um projeto de exemplo construído durante a palestra.">TDD: Test Driven Development em PHP</td>
					<td class="descricao rightColumn" data-owner="Thiago Paes" data-desc="Apresentando o Yaf - Yet Another Framework, um framework MVC que roda sob uma extensão do PHP.">Yaf - um framework que roda sob uma extensão</td>
				</tr>
				<tr>
				    <th class="span1">12:00</th>
					<td colspan="2" style="text-align: center;">Almoço</td>
				</tr>
				<tr>
				    <th class="span1">13:30</th>
					<td class="descricao" data-owner="Augusto das Neves" data-desc="Saiba como melhorar o design de seu código, tornando-o mais simples, otimizado e organizado utilizando alguns princípios básicos da Metodologia 5S. Utilizando ferramentas para cada um dos princípios.">5 maneiras de melhorar seu código</td>
					<td rowspan="3" class="descricao rightColumn" data-owner="Marcel Araujo" data-desc="Se você deseja realizar a certificação PHP 5.3 e está em dúvidas se o investimento vale a pena ou qual é a melhor maneira de estudar e ser aprovado, não deixe de participar desta palestra e conferir dicas importantes que farão a diferença no momento da prova.">PHP 5.3 - O caminho das pedras</td>
				</tr>
				<tr>
				    <th class="span1">13:50</th>
					<td class="descricao" data-owner="Alexandre Gaigalas" data-desc="Um guia rápido de como ser produtivo com UML sem sentir azia e má digestão.">UML: As Partes Boas</td>
				</tr>
				<tr>
				    <th class="span1">14:10</th>
					<td class="descricao" data-owner="Thiago Paes" data-desc="Mostrando formas interessantes de uso do PHP no dia-a-dia, sem a necessidade de um servidor web.">PHP além do ambiente LAMP</td>
				</tr>
				<tr>
				    <th class="span1">14:30</th>
				    <td class="descricao" data-owner="Luís Otávio Cobucci Oblonczyk" data-desc="Conheça uma abordagem fácil e eficaz para gerenciar as dependências de cada classe, simplifique sua vida e aumente sua produtividade e qualidade do seu código.">Dependency Injection, WTF?</td>
					<td class="descricao rightColumn" data-owner="Rodrigo dos Santos" data-desc="O PHP é uma linguagem de programação que oferece grande poder de criação para seus desenvolvedores. Porém, isto pode se tornar um grande problema caso não haja preocupação com a segurança. Nesta palestra conheceremos como são realizados os principais ataques à aplicações PHP e como podemos evitá-los.">Segurança em aplicações PHP</td>
				</tr>
				<tr>
				    <th class="span1">15:30</th>
					<td rowspan="3" class="descricao" data-owner="Elton Minetto" data-desc="Apresentação do micro framework Silex, APIs e como criá-las usando o framework.">Criando APIs usando o micro framework Silex</td>
					<td class="descricao rightColumn" data-owner="Maira Stella da Silva" data-desc="Criar testes automatizados em aplicações Web é tão fácil, que até uma loira consegue. Na palestra, será apresentada a praticidade e as vantagens da criação de testes automatizados utilizando a ferramenta Selenium. Se uma loira consegue, você também vai conseguir!">O que uma loira pode ensinar sobre testes automatizados em aplicações Web</td>
				</tr>
				<tr>
				    <th class="span1">15:50</th>
					<td class="descricao rightColumn" data-owner="Alexandre Gaigalas" data-desc="Todos nós gostamos de NoSQL: a idéia de utilizar bancos de dados apropriados para cada projeto. Veja como o MySQL já faz isso há anos e quais suas limitações.">MySQL Para Quem Gosta de NoSQL</td>
				</tr>
				<tr>
				    <th class="span1">16:10</th>
					<td class="descricao rightColumn" data-owner="Gustavo das Neves" data-desc="Nesta palestra irei abordar conceitos e técnicas de segurança para implementação em PHP. Mostrarei exemplos de como os próprios desenvolvedores criam falhas em seus sistemas e ferramentas para detectar e corrigir.">Segurança e PHP - Blinde seu código de você mesmo!</td>
				</tr>
				<tr>
				    <th class="span1">16:30</th>
					<td class="descricao" data-owner="Augusto Pascutti" data-desc="Veremos algumas das técnicas mais comuns para tornar uma aplicação web escalável através de exemplos práticos, são elas: cache, load balancer e proxy reverso.">Como Escalar Aplicações Web</td>
					<td class="descricao rightColumn" data-owner="Flávio Silveira" data-desc="Seja o programador que você quer e pode ser.">Seja Excelente</td>
				</tr>
				<tr>
				    <th class="span1">17:30</th>
					<td class="descricao" data-owner="Alex Piaz" data-desc="Se você precisa abrir os dados da sua organização ou prover Api's ReST(Ful) de maneira fácil e rápida, não pode perder esta chance de conhecer o FRAPI: Um framework opensource desenvolvido em PHP especializado na criação de Api's. Mais informações sobre o FRAPI podem ser obtidas em http://www.getfrapi.com/.">Criando APis (webservices ReSTFul) com FRAPI</td>
					<td></td>
				</tr>
			</tbody>
		</table>
    </div>
</div>
<div class="row">
    <div class="span9" style="text-align: center;">
        <h4>Minicursos</h4>
    </div>
</div>
<div class="row">
    <div class="span5">
        <table class="table table-striped">
			<thead>
				<tr>
					<th class="span1"></th>
					<th>Laboratório</th>
				</tr>
			</thead>
			<tbody>
				<tr>
				    <th class="span1">09:00</th>
					<td class="descricao" data-owner="Flávio Silveira" data-desc="Comece com o pé direito dentro de um dos frameworks mais usados de PHP. Construa suas aplicações dentro de uma estrutura organizada e poderosa com o auxílio da Zend Tool.">Começando bem com o ZF</td>
				</tr>
				<tr>
				    <th class="span1">14:00</th>
					<td class="descricao" data-owner="Domingos Teruel e Luís Otávio Cobucci Oblonczyk" data-desc="Venha aprender a criar testes de unidades de forma prática e simples, seguindo as boas práticas e os mandamentos do TDD!">TDD the right way</td>
				</tr>
			</tbody>
		</table>
    </div>
</div>
<div class="row">
    <div class="span9"><strong>Obs:</strong> grade sujeita a alterações.</div>
</div>
<script type="text/javascript">
<!--
$(document).ready(function () {
	$('.descricao').popover(
		{
			placement: function ()
			{
			    if ($(this.$element).hasClass('rightColumn')) {
			        return 'left';
			    }

			    return 'right';
			},
			title: function ()
			{
				return $(this).text();
			},
			content: function ()
			{
			    var content = '<h5>Palestrante(s)</h5><h6>'
			                  + $(this).attr('data-owner') + '</h6>'
			                  + '<h5>Descrição</h5>'
			                  + '<p style="text-align: justify;">' + $(this).attr('data-desc') + '</p>'

			    return content;
			}
	    }
    ).css('cursor', 'pointer');

});
//-->
</script>
<?php } ?>