<div class="hero-unit" style="padding: 30px;">
    <h2>Grade de palestras</h2>
    <h3><?php echo $this->getEvent()->getName(); ?></h3>
    <div style="margin-top: 15px;">
        <p>As palestras estão em avaliação, aguarde!</p>
    </div>
</div>
<div class="row">
    <div class="span9">
        <h2>Você pode ajudar!</h2>
        <p>
            Sim, você também pode colaborar no processo de avaliação de palestras!<br />
            Para fazer isto, basta dar sua opinião <a href="<?php echo $this->getBaseUrl() ?>/call4papers/feedback">aqui</a>!
        </p>
    </div>
</div>