<?php /* @var $this PHPSC\Conference\UI\Pages\Talks\Index */ ?>
<?php if (!$this->hasApprovedTalks()) { ?>
<div class="jumbotron" style="padding: 30px;">
    <h2>Programação</h2>
    <h3><?php echo $this->event->getName(); ?></h3>
    <div style="margin-top: 15px;">
        <p>As submissões estão em avaliação, aguarde!</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Você pode ajudar!</h2>
        <p>
            Sim, você também pode colaborar no processo de avaliação!<br />
            Para fazer isto, basta dar sua opinião <a href="<?php echo $this->getUrl('call4papers/feedback') ?>">aqui</a>!
        </p>
    </div>
</div>
<?php } else { ?>
<div class="row title">
    <div class="col-md-12">
        <h1>Programação</h1>
        <h3><?php echo $this->event->getName(); ?></h3>
    </div>
</div>
<?php for ($date = $this->event->getStartDate(); $date <= $this->event->getEndDate(); $date->modify('+1 day')) { ?>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped" id="talks-<?= $date->format('Y-m-d'); ?>">
                <caption style="font-size: 130%; margin: 0; font-weight: bold;"><?= $date->format('d/m/Y'); ?></caption>
            </table>
        </div>
    </div>
<?php } ?>
<div class="row">
    <div class="col-md-12"><strong>Obs:</strong> grade sujeita a alterações.</div>
</div>
<?php } ?>
<?= $this->getWindow(); ?>