<div class="modal fade" id="talkWindow" tabindex="-1" role="dialog" aria-labelledby="talkWindow" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3><span></span><br /><small style="font-size: 87%;"></small></h3>
            </div>
            <div class="modal-body">
                <div style="padding-top: 0px;">
                    <div class="row">
                        <div class="col-md-7">
                            <div id="speakers" class="form-group">
                                <label></label>
                            </div>
                        </div>
                        <div class="col-md-5" id="community-evaluation" style="display: none"></div>
                    </div>
                    <div class="form-group">
                        <label>Resumo</label>
                        <p id="shortDescription" class="well"></p>
                    </div>
                    <div class="form-group" id="talkTags">
                        <label>Tags</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Fechar</a>
            </div>
        </div>
    </div>
</div>