
<div class="row title">
    <div class="span9">
        <h1>Sobre o Evento</h1>
    </div>
</div>
<div class="row">
    <div class="span8">
    	<h2>PHPSC Conference 2012</h2>
    	<ul>
    		<li>Data: 27 de outubro de 2012</li>
    		<li>Local: <a href="/venue">Univali, São José, SC</a></li>
    		<li><a href="/registration">Inscrições</a></li>
    	</ul>
    </div>
</div>
<div class="row">
    <div class="span8">
        <h2>Conhecendo um pouco mais sobre o PHPSC Conf</h2>
        <p>O PHPSC Conf tem como objetivo principal discutir melhores práticas sobre a tecnologia PHP e áreas co-relatas como Design, Técnicas de Desenvolvimento, Banco de Dados, Software Livre etc. </p>
	    <p>O evento acontece anualmente, sempre em uma cidade diferente do estado, e é realizado em parceria com uma instituição de ensino do local do município aonde o mesmo venha a ocorrer. </p>
        <p>Isto está de acordo com os objetivos do grupo, que é percorrer o estado de forma que mais pessoas possam participar, apresentando o PHP através de profissionais que realmente utilizam a linguagem, e que levem a qualidade técnica das informações discutidas. Trazendo, para este fim, palestrantes de fora do estado e que são referência no Brasil, mas também contando com palestrantes locais. O evento não tem fins lucrativos. As cotas de patrocínio levantadas são para cobrir custos com palestrantes como deslocamento, hospedagem e alimentação, pois o PHPSC não é uma instituição com fins lucrativos e também por não ser uma pessoa juridicamente constituída. Sendo o trabalho de organização deste evento, realizado de forma voluntária pelos seus integrantes. </p>
    </div>
</div>