<div class="row title">
    <div class="span9">
        <h1>Fale conosco</h1>
    </div>
</div>
<div class="row">
    <div class="span5">
        <h2>Sobre qualquer coisa, sua opinião será sempre importante</h2>
        <p>
        A sua opinião não é apenas necessária, ela é a base para nossas ações evolutivas e corretivas. Jamais se sinta acanhado em entrar em contato conosco, as críticas e sugestões que recebemos, sempre contribuem de uma forma outra para o fortalecimento da comunidade, e é isso que precisamos. <br/>O que gostaria de dizer?            
        </p>
    </div>
    <div class="span4">
        <h2>Formas de contatar-nos</h2>
        <p>
            Por e-mail (É o mesmo endereço para onde esse formulário será enviado): phpscconf2012@phpsc.com.br
            twitter: PHP_SC <br>
            facebook: http://www.facebook.com/phpsc<br>
        </p>        
    </div>
</div>