<div class="row title">
    <div class="span9">
        <h1>Fale conosco</h1>
    </div>
</div>
<div class="row">
    <div class="span5">
        <h2>Sobre qualquer coisa, sua opinião será sempre importante</h2>
        <p>
        A sua opinião não é apenas necessária, ela é a base para nossas ações evolutivas e corretivas. Jamais se sinta acanhado em entrar em contato conosco.             
        </p>
        <p>
        As críticas e sugestões que recebemos, sempre contribuem de uma forma outra para o fortalecimento da comunidade, e é isso que precisamos.            
        </p>
        <p>
            O que gostaria de dizer?
        </p>
    </div>
    <div class="span4">
        <h2>Formas de contatar-nos</h2>
        <p>
            <a href='https://twitter.com/PHP_SC' title='Perfil Oficial do PHPSC no Twitter'>Twitter</a><br>
            <a href='http://tinyurl.com/phpsc' title='Perfil Oficial do PHPSC no Twitter'>Facebook</a><br>
        </p>        
    </div>
</div>