<div class="hero-unit">
    <h1>PHP SC Conf 2012</h1>
    <p>É chegada a hora de mais um PHP SC Conf. Um dos eventos mais esperados da comunidade PHP de Santa Catarina.</p>
    <p><a class="btn btn-primary btn-large">Maiores Informações &raquo;</a></p>
</div>
<div class="row">
    <div class="span5">
        <h2>Chamada de Trabalhos</h2>
        <p>Está aberta a chamada de trabalhos, não perca tempo e envie sua proposta de palestra!</p>
        <p><a class="btn" href="/">Maiores Informações &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>Inscrições</h2>
        <p>            
           Fique ligado, pois em breve abriremos as inscrições para o evento e as inscrições feitas antecipadamente terão um valor mais bacana. 
           <?php
           //Aproveite a oportunidade de pagar um pouquinho menos e faça agora mesmo a sua inscrição para o evento sobre PHP mais bacana do estado.
           ?>
        </p>
        <p><a class="btn" href="#">Maiores Informações &raquo;</a></p>
    </div>
</div>