<div id="fb-root"></div>
<script type="text/javascript">
(
function(d, s, id)
{
    var js, fjs = d.getElementsByTagName(s)[0];

    if (d.getElementById(id)) {
	    return;
    }

    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div class="hero-unit">
    <h1>PHPSC Conf 2012</h1>
    <p>
        Sábado, 27 de outubro de 2012, Univali, São José, SC.<br />
        Das 8h às 19h.
    </p>
    <p><a class="btn btn-primary btn-large" href="<?php echo $this->getUrl('about'); ?>">Maiores Informações &raquo;</a></p>
</div>
<div class="row">
    <div class="span5">
        <h2>Chamada de Trabalhos</h2>
        <p>Finalizamos a chamada de trabalhos e estamos em processo de avaliação, quer conferir o que foi submetido?</p>
        <p><a class="btn" href="<?php echo $this->getUrl('call4papers/feedback'); ?>">Maiores Informações &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>Inscrições</h2>
        <p>
           As inscrições já foram iniciadas, garanta agora sua participação no evento, aproveitando o preço
           mais bacana para inscrições antecipadas!
        </p>
        <p><a class="btn" href="<?php echo $this->getUrl('registration'); ?>">Maiores Informações &raquo;</a></p>
    </div>
</div>
<div class="row">
    <div class="span9 title">
        <h3>PHPSC nas redes sociais</h3>
    </div>
</div>
<div class="row">
    <div class="span5" id="twitterBox"></div>
   <div class="span4 fb-like-box"
       data-href="https://www.facebook.com/pages/PHP-Santa-Catarina/478179522208583"
       data-height="250" data-show-faces="true"
       data-stream="false" data-header="false">
    </div>
</div>
