<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <meta charset="utf-8">
        <title>PHPSC Conference - Status</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Acompanhe o status das inscrições e presenças ao vivo!">
        <link href="<?php echo $this->getBaseUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->getBaseUrl(); ?>/css/main.css" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->getBaseUrl(); ?>';
    	</script>
    	<script src="<?php echo $this->getBaseUrl(); ?>/js/jquery-1.7.2.min.js" type="text/javascript"></script>
    	<script src="<?php echo $this->getBaseUrl(); ?>/js/bootstrap.min.js" type="text/javascript"></script>
    	<script src="<?php echo $this->getBaseUrl(); ?>/js/status.js" type="text/javascript"></script>
    	<style type="text/css">
            body {
            	background-color: #F5F5F5;
            }

            #nrInscricoes, #nrPresencas {
                color: #27519d;
                text-align: center;
            }

            h4 {
            	padding-top: 35px;
            }
    	</style>
    </head>

    <body>
    	<div class="container" style="padding-top: 30px;">
    	    <div class="row">
                <div class="span12" style="text-align: center;">
                    <img src="<?php echo $this->getBaseUrl(); ?>/img/logo-grande.png" alt="PHPSC Conference 2012" height="250" />
                </div>
            </div>
    	    <div class="row" style="padding-top: 30px">
                <div class="span2 offset3"><h2 id="nrInscricoes"></h2></div>
                <div class="span2 offset2"><h2 id="nrPresencas"></h2></div>
            </div>
    	    <div class="row" style="padding-top: 150px">
                <div class="span1 offset2"><h4>Realização</h4></div>
                <div class="span2"><img src="<?php echo $this->getBaseUrl(); ?>/img/logo-phpsc.png" alt="PHPSC" height="90" style="margin-left: 30px" /></div>
                <div class="span1 offset1"><h4>Patrocínio</h4></div>
                <div class="span3"><img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_softnex.png" alt="Softnex Tecnologia" height="90" /></div>
            </div>
    	    <div class="row" style="padding-top: 30px">
                <div class="span1 offset1"><h4>Apoio</h4></div>
                <div class="span10">
                    <img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_univali.gif" alt="Softnex Tecnologia" height="90" />
                    <img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_novatec.gif" alt="Softnex Tecnologia" height="90" />
                    <img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_schoolofnet.gif" alt="Softnex Tecnologia" height="90" />
                    <img src="<?php echo $this->getBaseUrl(); ?>/img/supporters/logo_zfnapratica.gif" alt="Softnex Tecnologia" height="90" />
                </div>
            </div>
        </div>
    </body>
</html>