<div class="row title">
    <div class="span9">
        <h1>O Local</h1>
    </div>
</div>
<div class="row">
    <div class="span5">
    	<div id="mapContent">
	        <div id="mapEvento" style="width: 100%; height:250px; border:1px solid #ccc;"></div>
    	</div>
        <p>
        	<div id="address"></div> 
        </p>
        <p>
        	<a class="btn" href="#">Detalhes do Evento</a>
		</p>
    </div>
    <div class="span4">
    	
    </div>
</div>
<script type="text/javascript">
    var lat = -27.64770;
    var lng = -48.47928;
</script>