<div class="row title">
    <div class="span9">
        <h1>O Local</h1>
    </div>
</div>
<div class="row">
    <div class="<?php echo $this->displayMap() ? 'span4' : 'span9'; ?>">
        <p>Esse ano, o evento será realizado em São José (ao lado de Florianópolis) na UNIVALI.</p>
        <img src="http://www.univali.br/uploads/temp/telefones/saojose.jpg" alt="UNIVALI Campus São José" />
        <p style="margin-top: 10px;">
            <strong>Campus São José</strong><br/>
            Rodovia SC 407 - KM4<br />
            Sertão do Maruim - São José - Santa Catarina<br />
        </p>
        <h3 style="margin-bottom: 5px;">Como chegar?</h3>
        <ul>
            <li><a href="http://goo.gl/maps/nzwiD" target="_blank">Desde o aeroporto</a></li>
            <li><a href="http://goo.gl/maps/Y2ris" target="_blank">Terminal Rita Maria</a></li>
            <li><a href="http://goo.gl/maps/WXJoh" target="_blank">Desde a BR 101 (Norte)</a></li>
            <li><a href="http://goo.gl/maps/IbB9l" target="_blank">Desde a BR 101 (Sul)</a></li>
        </ul>
    </div>
    <?php if ($this->displayMap()) { ?>
    <div class="span5">
        <ul class="thumbnails">
            <li class="span5">
                <div class="thumbnail">
                    <div id="mapEvento"></div>
                    <h6 id="address"></h6>
                </div>
            </li>
        </ul>
    </div>
    <?php } ?>
    <div class="span9">
        <h3>Transporte</h3>
        <p>Contratamos uma empresa para fazer o transporte dos palestrantes e participantes do evento.</p>
        <p>O ônibus irá parar nos seguintes locais:</p>
        <ol>
            <li>Florianópolis - Centro - Largo da Alfândega</li>
            <li>São José - Kobrasol - Em frente ao McDonalds</li>
            <li><del title="Local removido por falta de interessados">Palhoça - Centro - Praça Sete de Setembro</del></li>
        </ol>
        <p>
            O horário de saída de Florianópolis é 7h45min, para que consiga percorrer o trajeto todo e chegar a tempo ao evento.<br />
            O transporte custará R$ 5,00 para os participantes (ida e volta).
        </p>
        <p>
            Por motivos de organização, pedimos aos interessados que preencham o
            seguinte <a href="https://docs.google.com/spreadsheet/viewform?formkey=dHdSeUUyYWM1ckhQS0Jmbk5ZM3llZmc6MQ" target="_blank">formulário</a>.
        </p>
    </div>
    <div class="span9">
        <h3>Hospedagem</h3>
        <p>Os seguintes hotéis são próximos do evento ou dos pontos de encontro do transporte que contratamos (os preços aqui listados foram consultados em 16/10/2012):</p>
        <div class="row" style="margin-top: 15px;">
            <div class="span4">
                <h4>
                    <a href="http://www.hotelitaguacu.com.br/novo/" target="_blank">Hotel Itaguaçu</a>
                </h4>
                <p>
                    Av. Gov. Ivo Silveira, 3861, Florianópolis<br />
                    (48) 3954 2600
                </p>
                <ul>
                    <li>Single: R$ 69,00</li>
                    <li>Duplo: R$ 114,00</li>
                    <li>Triplo: R$ 145,00</li>
                    <li>Quadruplo: R$ 184,00</li>
                </ul>
            </div>
            <div class="span4 offset1">
                <h4>
                    <a href="http://www.slavierohoteis.com.br/br/palhoca/slaviero-executive-viacatarina_8_hoteis.aspx" target="_blank">Hotel Slaviero</a>
                </h4>
                <p>
                    Rua Atilio Pedro Pagani, 300, Palhoça<br />
                    (48) 3086 9006
                </p>
                <ul>
                    <li>Luxo Casal: R$ 120,00</li>
                    <li>Luxo Duplo Solteiro: R$ 120,00</li>
                    <li>Luxo Superior Casal Não Fumante: R$ 130,00</li>
                    <li>Luxo Superior Duplo Solteiro Não Fumante: R$ 130,00</li>
                </ul>
            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="span4">
                <h4>
                    <a href="http://www.ibis.com/pt-br/hotel-6667-ibis-sao-jose/index.shtml" target="_blank">Ibis Hotel São José</a>
                </h4>
                <p>
                    Rua Domingos André Zanini, 333, São José<br />
                    (48) 3211 1200
                </p>
                <ul>
                    <li>Cama de casal ou duas camas de solteiro: R$ 119,00</li>
                </ul>
            </div>
            <div class="span4 offset1">
                <h4>
                    <a href="http://www.zionhotel.com.br/" target="_blank">Hotel Zion</a>
                </h4>
                <p>
                    Rua Tiradentes, 04, São José<br />
                    (48) 3259 0002
                </p>
                <ul>
                    <li>Single: R$ 120,00</li>
                    <li>Duplo: R$ 160,00</li>
                    <li>Triplo: R$ 180,00</li>
                </ul>
            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="span4">
                <h4>
                    <a href="http://www.hotellunes.com.br/port/index.html" target="_blank">Hotel Lunes</a>
                </h4>
                <p>
                    Av. Altamiro Di Bernardi, 400, São José<br />
                    (48) 3241 4444
                </p>
                <ul>
                    <li>Single: R$ 95,00</li>
                    <li>Duplo: R$ 115,00</li>
                    <li>Triplo: R$ 135,00</li>
                </ul>
            </div>
            <div class="span4 offset1">
                <h4>
                    <a href="http://www.hotelkennedy.com.br/site.html" target="_blank">Hotel Kennedy</a>
                </h4>
                <p>
                    Av. Presidente Kennedy, 300, São José<br />
                    (48) 3241 0011
                </p>
                <ul>
                    <li>Single: R$ 90,00</li>
                    <li>Single (luxo): R$ 99,00</li>
                    <li>Duplo: R$ 110,00</li>
                    <li>Duplo (luxo): R$ 119,00</li>
                    <li>Triplo: R$ 139,00</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php if ($this->displayMap()) { ?>
<script type="text/javascript">
    var lat = <?php echo $this->getEvent()->getLocation()->getLatitude(); ?>;
    var lng = <?php echo $this->getEvent()->getLocation()->getLongitude(); ?>;
</script>
<?php } ?>