<div class="row title">
    <div class="span9">
        <h1>O Local</h1>
        Esse ano, o evento será realizado em São José (ao lado de Florianópolis) na UNIVALI.
    </div>
</div>
<div class="row">
    <div class="span5">

        <p>
        <b>Campus São José - Unidade Kobrasol</b><br/>
        Rua Adhemar da Silva, s/n - Kobrasol - São José/SC
        <br/>(Rua da Caixa Econômica, em frente à Previdência Social)
        </p>

    </div>
    <div class="span4">
        <ul class="thumbnails">
            <li class="span4">
                <div class="thumbnail">
                    <div id="mapEvento"></div>
                    <h6 id="address"></h6>
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="row title">
    <div class="span9">
        <h1>Como chegar?</h1>
         <p>
            <b>Desde o aeroporto</b><br/>
         </p>
         <p>
            <b>Terminal Rita Maria</b><br/>
         </p>
        <p>
            <b>Desde a BR 101</b><br/>
         </p>

    </div>
</div>

<div class="row title">
    <div class="span9">
        <h1>Hospedagem</h1>
        Os hotéis abaixo listados, apoiam a realização do evento e colaboram com preços mais baixos para os participantes.
    </div>
</div>
<script type="text/javascript">
    var lat = -27.590016;
    var lng = -48.61164;
</script>