<?php /* @var $this PHPSC\Conference\UI\Footer */ ?>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->renderSponsors(); ?>
				<hr>
				<div class="row">
					<div class="col-md-12">
						<div class="col-md-5">
							<p class="muted">
								<strong>PHPSC</strong>
								<small>Grupo de Usuários de PHP do Estado de Santa Catarina</small>
							</p>
						</div>
						<div class="col-md-7">
							<div class="pull-right">
								<a href="http://groups.yahoo.com/group/php-santacatarina/" target="_blank" title="Grupo PHPSC no Yahoo! Grupos">
									<img src="<?php echo $this->getUrl('img/social-icons/glyphicons_social_04_yahoo.png'); ?>" />
								</a>
								<a href="https://www.twitter.com/PHP_SC/" target="_blank" title="PHPSC no Twitter">
									<img src="<?php echo $this->getUrl('img/social-icons/glyphicons_social_31_twitter.png'); ?>" />
								</a>
								<a href="https://www.facebook.com/groups/430320340321421/" target="_blank" title="Grupo PHPSC no Facebook">
									<img src="<?php echo $this->getUrl('img/social-icons/glyphicons_social_30_facebook.png'); ?>" />
								</a>
								<a href="http://www.phpsc.com.br/" target="_blank" title="Blog PHPSC">
									<img src="<?php echo $this->getUrl('img/social-icons/glyphicons_social_09_wordpress.png'); ?>" />
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>



