<?php /* @var $this PHPSC\Conference\UI\Main */ ?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <meta charset="utf-8">
        <title>PHPSC Conference</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A maior conferência de PHP de Santa Catarina">
        <meta name="author" content="Grupo de Usuários de PHP de Santa Catarina">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
        <link href="<?php echo $this->getUrl('css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->getUrl('css/main.css'); ?>" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="<?php echo $this->getUrl('js/vendor/html5shiv.js'); ?>"></script>
            <script src="<?php echo $this->getUrl('js/vendor/respond.min.js'); ?>"></script>
        <![endif]-->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->getBaseUrl(); ?>';
    	</script>
    </head>

    <body>
    	<div id="wrap">
            <?php echo $this->renderNavigation(); ?>

        	<div id="main" class="container clear-top">
        	   <div class="row">
        	       <?php if ($this->event->hasLogo()) { ?>
        	       <div class="col-md-2">
                	   <a href="<?= $this->getBaseUrl(); ?>">
                            <img alt="PHPSC Conference"
                                src="<?= $this->getUrl('event/' . $this->event->getId()); ?>?w=180&h=170" />
                        </a>
                    </div>
                    <?php } ?>
                	<div class="col-md-<?= $this->event->hasLogo() ? 10 : 12; ?>">
                	   <h1 style="padding-top: 55px; text-align: right;">
                	       PHPSC Conference<br />
                	       <small>A maior conferência de PHP de Santa Catarina</small>
            	       </h1>
                    </div>
                </div>
        	    <div class="row" style="margin-top: 20px">
                    <div class="col-md-12">
                        <?php echo $this->renderContent(); ?>
                    </div>
                </div>
            </div>

            <?php echo $this->renderFooter(); ?>
        </div>
        <?php foreach ($this->getScripts() as $script) { ?>
            <script src="<?php echo $script; ?>" type="text/javascript"></script>
        <?php } ?>
    </body>
</html>
