<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span> <span
                class="icon-bar"></span> <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
		<?php foreach ($this->getOptions() as $option) { ?>
			<li>
                <a href="<?= $this->getUrl($option[1]); ?>"><?= $option[0]; ?></a>
            </li>
		<?php } ?>
		</ul>
		<div class="nav navbar-nav navbar-right">
	    <?php if ($user = $this->getTwitterUser()) { ?>
            <div class="btn-group" style="margin-top: 4px; margin-right: 7px;">
                <a class="btn dropdown-toggle" data-toggle="dropdown" style="padding: 1px">
                    <img alt="<?= $user->screen_name; ?>"
                        title="Logado como @<?= $user->screen_name; ?>"
                        src="<?= $user->profile_image_url; ?>"
                        height="36" width="36">
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?= $this->getUrl('user'); ?>">Meus dados</a></li>
                    <li><a href="<?= $this->getUrl('call4papers/submissions'); ?>">Trabalhos submetidos</a></li>
                    <li class="divider"></li>
                    <li><a href="<?= $this->getUrl('oauth/logoff'); ?>">Sair</a></li>
                </ul>
            </div>
		    <?php } else { ?>
                <a class="btn btn-default" style="margin-top: 7px; margin-right: 7px;"
                    href="<?= $this->getUrl('oauth/redirect'); ?>">
                    <span class="glyphicon glyphicon-user"></span> Logar
                </a>
            </a>
			<?php } ?>
		</div>
    </div>
</nav>