<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span> <span
                class="icon-bar"></span> <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
		<?php foreach ($this->getOptions() as $option) { ?>
			<li>
                <a href="<?= $this->getUrl($option[1]); ?>"><?= $option[0]; ?></a>
            </li>
		<?php } ?>
		</ul>
		<div class="nav navbar-nav navbar-right">
        <?php if ($profile = $this->getProfile()) { ?>
            <div class="btn-group" style="margin-top: 4px; margin-right: 7px;">
                <a class="btn dropdown-toggle" data-toggle="dropdown" style="padding: 1px">
                    <img alt="<?= $profile->getUsername(); ?>"
                        title="Logado como @<?= $profile->getUsername(); ?>"
                        src="<?= $profile->getAvatar(); ?>"
                        height="36" width="36">
                </a>
                <?= $this->getMenu(); ?>
    		</div>
        <?php } else { ?>
            <div class="btn-group" style="margin-top: 7px; margin-right: 7px;">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-user"></span> Logar <span class="caret"></span>
                </button>
                <?= $this->getMenu(); ?>
    		</div>
		<?php } ?>
		</div>
    </div>
</nav>