<?php /* @var $this PHPSC\Conference\UI\Sponsors */ ?>
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h3>Realização</h3>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-2" style="padding-top: 10px; text-align: center; line-height: 80px;">
    	<a href="http://www.phpsc.com.br/" target="_blank" title="Grupo de Usuários de PHP de Santa Catarina">
        	<img src="<?php echo $this->getUrl('img/logo-phpsc.png'); ?>" height="80" alt="Grupo de Usuários de PHP de Santa Catarina">
		</a>
	</div>
	<?php if ($this->event->getLocation()->hasLogo()) { ?>
	<div class="col-md-2" style="padding-top: 10px; text-align: center; line-height: 80px;">
    	<a href="<?= $this->event->getLocation()->getWebsite(); ?>" target="_blank" title="<?= $this->event->getLocation()->getName(); ?>">
        	<img src="<?php echo $this->getUrl('location/' . $this->event->getLocation()->getId()); ?>?h=80&w=160"
        	   alt="<?= $this->event->getLocation()->getName(); ?>">
		</a>
	</div>
	<?php } ?>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h3>Patrocínio</h3>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-2" style="padding-top: 10px; text-align: center; line-height: 80px;">
    	<a href="http://meritt.com.br/" target="_blank" title="Meritt Informação Educacional">
        	<img src="<?php echo $this->getUrl('img/supporters/logo_meritt.png'); ?>" width="160" alt="Meritt Informação Educacional">
		</a>
	</div>
</div>
<div id="supportersContainer" class="hide">
    <div class="row">
    	<div class="col-md-12">
    		<div class="page-header">
    			<h3>Apoio</h3>
    		</div>
    	</div>
    </div>
</div>