<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h3>Realização</h3>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-2" style="padding-top: 10px; text-align: center;">
    	<a href="http://www.phpsc.com.br/" target="_blank" title="Grupo de Usuários de PHP de Santa Catarina">
        	<img src="<?php echo $this->getUrl('img/logo-phpsc.png'); ?>" height="95" alt="Grupo de Usuários de PHP de Santa Catarina">
		</a>
	</div>
	<div class="col-md-2" style="padding-top: 10px; text-align: center;">
    	<a href="http://www.unochapeco.edu.br/" target="_blank" title="Universidade Comunitária da Região de Chapecó - UNOCHAPECÓ">
        	<img src="<?php echo $this->getUrl('img/supporters/logo_unochapeco.png'); ?>" alt="Universidade Comunitária da Região de Chapecó - UNOCHAPECÓ">
		</a>
	</div>
</div>